### PR TITLE
connect provider hot fix. dropdown menu options changed

### LINKED ISSUE #117: ConnectProvider hot fix
BUG: connect provider modal not opening.

### PR DESCRIPTION
**Pull request by claireolmstead**
closes #117

### CODE REVIEW

File: src/components/ConnectProvider.svelte [hunk 1]
```diff
@@ -1,19 +1,20 @@
...
     <h2 class="section-title-underlined">Connect Provider</h2>
     <!-- Select a network dropdown goes here -->
     <!-- Should default to current network -->
-    <DropDownMenu label="Select a Network" options={{ option1: 'option1' }} />
+    <DropDownMenu label="Select a Network" options={['option1']} />
 
     <!-- Select a control provider key goes here -->
     <!-- Should default to current key -->
-    <DropDownMenu label="Select a Control Provider Key" options={{ option1: 'option1' }} />
+    <DropDownMenu label="Select a Control Provider Key" options={['option1', 'option2']} />
```
Comment (enddynayn) [inline src/components/ConnectProvider.svelte:17]: 👍

**Review by enddynayn — APPROVED** [review]
👍 great!
